// Tidy3dExporter.cpp
#include "Tidy3dExporter.h"
#include "../core/Project.h"

#include <QFile>
#include <QTextStream>

using namespace ofd;

static QString py(double v) { return QString::number(v, 'g', 10); }

QString Tidy3dExporter::generatePython(const Project &p)
{
    QString text;
    QTextStream out(&text);

    const GeneralOpts &g = p.general();
    const OpticalOpts &o = p.optical();

    const double c0 = 2.99792458e8;
    const double lam0 = (o.lambdaMin + o.lambdaMax) / 2 * 1e-9;   // m
    const double f0 = c0 / lam0;
    const double fmin = c0 / (o.lambdaMax * 1e-9);
    const double fmax = c0 / (o.lambdaMin * 1e-9);

    out << "# Generated by OpenFDTD-X — tidy3d cloud submission script\n";
    out << "# project: " << (g.title.isEmpty() ? p.tidy3d().projectName : g.title) << "\n";
    out << "# API key: configure once with `tidy3d configure` (not embedded here)\n";
    out << "import numpy as np\n";
    out << "import tidy3d as td\n";
    out << "import tidy3d.web as web\n\n";

    // simulation region from the mesh
    double lo[3], hi[3];
    for (int a = 0; a < 3; ++a) {
        lo[a] = p.mesh(a).min();
        hi[a] = p.mesh(a).max();
    }
    out << "sim_center = (" << py((lo[0]+hi[0])/2) << ", "
        << py((lo[1]+hi[1])/2) << ", " << py((lo[2]+hi[2])/2) << ")\n";
    out << "sim_size = (" << py(hi[0]-lo[0]) << ", " << py(hi[1]-lo[1])
        << ", " << py(hi[2]-lo[2]) << ")\n\n";

    // materials
    out << "# materials (material id 0=vacuum, 1=PEC are built in)\n";
    out << "mediums = {\n";
    out << "    0: td.Medium(permittivity=1.0),\n";
    out << "    1: td.PECMedium(),\n";
    int mid = 2;
    for (const Material &m : p.materials()) {
        if (m.type == 2) {
            out << "    # material " << mid << " is dispersive in OpenFDTD "
                   "(einf=" << py(m.einf) << ", a=" << py(m.ae)
                << ", b=" << py(m.be) << ", c=" << py(m.ce) << ")\n";
            out << "    # map it manually to td.PoleResidue / td.Drude:\n";
            out << "    " << mid << ": td.Medium(permittivity=" << py(m.einf) << "),\n";
        } else {
            out << "    " << mid << ": td.Medium(permittivity=" << py(m.epsr)
                << ", conductivity=" << py(m.esgm) << "),\n";
        }
        ++mid;
    }
    out << "}\n\n";

    // geometry
    out << "structures = [\n";
    for (const Geometry &ge : p.geometries()) {
        const double cx = (ge.g[0]+ge.g[1])/2, cy = (ge.g[2]+ge.g[3])/2,
                     cz = (ge.g[4]+ge.g[5])/2;
        const double sx = ge.g[1]-ge.g[0], sy = ge.g[3]-ge.g[2],
                     sz = ge.g[5]-ge.g[4];
        switch (ge.shape) {
        case 1:
            out << "    td.Structure(geometry=td.Box(center=(" << py(cx) << ", "
                << py(cy) << ", " << py(cz) << "), size=(" << py(sx) << ", "
                << py(sy) << ", " << py(sz) << ")), medium=mediums["
                << ge.materialId << "]),\n";
            break;
        case 2:
            out << "    td.Structure(geometry=td.Sphere(center=(" << py(cx)
                << ", " << py(cy) << ", " << py(cz) << "), radius="
                << py(qMax(qMax(sx, sy), sz) / 2)
                << "), medium=mediums[" << ge.materialId
                << "]),  # ellipsoid approximated as sphere\n";
            break;
        case 11: case 12: case 13: {
            const char axis = (ge.shape == 11) ? '0' : (ge.shape == 12) ? '1' : '2';
            const double len = (ge.shape == 11) ? sx : (ge.shape == 12) ? sy : sz;
            const double rad = (ge.shape == 11) ? qMax(sy, sz) / 2
                             : (ge.shape == 12) ? qMax(sx, sz) / 2
                                                : qMax(sx, sy) / 2;
            out << "    td.Structure(geometry=td.Cylinder(center=(" << py(cx)
                << ", " << py(cy) << ", " << py(cz) << "), axis=" << axis
                << ", length=" << py(len) << ", radius=" << py(rad)
                << "), medium=mediums[" << ge.materialId << "]),\n";
            break;
        }
        default:
            out << "    # shape code " << ge.shape
                << " (pillar/pyramid/cone) has no direct tidy3d primitive — "
                   "use td.PolySlab manually\n";
            break;
        }
    }
    out << "]\n\n";

    // source
    out << "pulse = td.GaussianPulse(freq0=" << py(f0) << ", fwidth="
        << py((fmax - fmin) / 2) << ")\n";
    if (p.planewave().enabled) {
        out << "source = td.PlaneWave(source_time=pulse, size=(td.inf, td.inf, 0),\n"
            << "                      center=sim_center, direction='+',\n"
            << "                      angle_theta=np.deg2rad(" << py(p.planewave().theta)
            << "), angle_phi=np.deg2rad(" << py(p.planewave().phi) << "))\n";
    } else if (!p.feeds().isEmpty()) {
        const Feed &f = p.feeds().first();
        const char *pol = (f.dir == 'X') ? "Ex" : (f.dir == 'Y') ? "Ey" : "Ez";
        out << "source = td.PointDipole(source_time=pulse, center=(" << py(f.x)
            << ", " << py(f.y) << ", " << py(f.z) << "), polarization='"
            << pol << "')\n";
    } else {
        out << "source = None  # no feed/planewave defined\n";
    }
    out << "\n";

    // monitors from the probes
    out << "freqs = np.linspace(" << py(fmin) << ", " << py(fmax) << ", "
        << qMax(2, o.lambdaDiv) << ")\n";
    out << "monitors = [\n";
    int mi = 0;
    for (const Probe &pr : p.probes())
        out << "    td.FieldMonitor(center=(" << py(pr.x) << ", " << py(pr.y)
            << ", " << py(pr.z) << "), size=(0, 0, 0), freqs=freqs, name='point"
            << ++mi << "'),\n";
    out << "]\n\n";

    const QString res = p.tidy3d().resolution;
    const int minSteps = (res == "fine") ? 20 : (res == "coarse") ? 6 : 10;
    out << "sim = td.Simulation(\n";
    out << "    center=sim_center,\n";
    out << "    size=sim_size,\n";
    out << "    grid_spec=td.GridSpec.auto(min_steps_per_wvl=" << minSteps << "),\n";
    out << "    structures=structures,\n";
    out << "    sources=[source] if source else [],\n";
    out << "    monitors=monitors,\n";
    out << "    run_time=" << py(g.maxiter * 1e-15) << ",  # adjust as needed\n";
    if (p.tidy3d().autoPml)
        out << "    boundary_spec=td.BoundarySpec.all_sides(boundary=td.PML()),\n";
    out << ")\n\n";
    out << "job = web.Job(simulation=sim, task_name="
        << '"' << p.tidy3d().projectName << '"' << ")\n";
    out << "print(f'estimated cost: {job.estimate_cost()} FlexCredits')\n";
    out << "# data = job.run(path='result.hdf5')\n";

    return text;
}

bool Tidy3dExporter::exportTo(const QString &path, const Project &project,
                              QString *err)
{
    QFile f(path);
    if (!f.open(QIODevice::WriteOnly | QIODevice::Text)) {
        if (err) *err = f.errorString();
        return false;
    }
    f.write(generatePython(project).toUtf8());
    return true;
}
